apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: rekrutteringsbistand-api
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/rekrutteringsbistand-api:{{version}}
  team: teamtag
  port: 8080
  ingresses:
    - https://arbeidsgiver.nais.adeo.no/rekrutteringsbistand-api/
  liveness:
    path: /rekrutteringsbistand-api/internal/actuator/health
    initialDelay: 20
  readiness:
    path: /rekrutteringsbistand-api/internal/actuator/health
    initialDelay: 20
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: LOGINSERVICE_OIDC_DISCOVERYURI
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/.well-known/openid-configuration
    - name: STILLING_API_URL
      value: https://pam-ad-api.nais.preprod.local/rekrutteringsbistand/
      #value: https://pam-ad-api.nais.preprod.local/rekrutteringsbistand/api/v1/ads
  prometheus:
    enabled: true
    path: /rekrutteringsbistand-api/internal/actuator/prometheus
  vault:
    enabled: false
