server.servlet.context-path: /rekrutteringsbistand-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

server:
  port: 9501

spring:
  profiles:
    active: local

---

spring:
  profiles: local
no.nav.security.oidc:
  issuers: loginservice-oidc
  issuer.loginservice-oidc:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: isso-localhost-idtoken

external:
  stilling-api:
    url: ${STILLING_API_URL:http://localhost:9014}
---

spring:
  profiles: mvc-test
no.nav.security.oidc:
  issuers: loginservice-oidc
  issuer.loginservice-oidc:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: isso-localhost-idtoken
external:
  stilling-api:
    url: http://localhost:8189

---

spring:
  profiles: dev

no.nav.security.oidc:
  issuers: loginservice-oidc
  issuer.loginservice-oidc:
    discoveryurl: ${LOGINSERVICE_OIDC_DISCOVERYURI}
    accepted_audience: ${LOGINSERVICE_OIDC_CLIENTID}
    cookie_name: isso-idtoken

external:
  stilling-api:
    url: ${STILLING_API_URL}

---

spring:
  profiles: prod

no.nav.security.oidc:
  issuers: loginservice-oidc
  issuer.loginservice-oidc:
    discoveryurl: ${LOGINSERVICE_OIDC_DISCOVERYURI}
    accepted_audience: ${LOGINSERVICE_OIDC_CLIENTID}
    cookie_name: isso-idtoken

external:
  stilling-api:
    url: ${STILLING_API_URL}
