server.servlet.context-path: /rekrutteringsbistand-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

spring:
  profiles:
    active: local

---

spring:
  profiles: local

---

spring:
  profiles: mvc-test

---

spring:
  profiles: dev

---

spring:
  profiles: prod



