apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: rekrutteringsbistand-stilling-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  receivers:
    slack:
      channel: 'inkludering-alerts-prod'
  alerts:
    - alert: rekrutteringsbistand-stilling-api
      severity: danger
      expr: sum(up{app="rekrutteringsbistand-stilling-api", job="kubernetes-pods"}) == 0
      for: 1s
      description: Appen er nede (ingen Kubernetes-pods er oppe)
      action: "https://logs.adeo.no/goto/628dd18b2a5496e186cb99f04cd6b32f"

    - alert: rekrutteringsbistand-stilling-api
      severity: danger
      expr: sum(increase(logd_messages_total{log_app="rekrutteringsbistand-stilling-api", log_level="Error"}[10m])) > 0
      for: 1s
      description: Appen har logget en error
      action: "https://logs.adeo.no/goto/628dd18b2a5496e186cb99f04cd6b32f"

    - alert: rekrutteringsbistand-stilling-api
      severity: warning
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="rekrutteringsbistand-stilling-api",log_level=~"Warning"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="rekrutteringsbistand-stilling-api"}[3m]))) > 5
      for: 5m
      description: Økning i warnings
      action: "https://logs.adeo.no/goto/628dd18b2a5496e186cb99f04cd6b32f"
