apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: rekrutteringsbistand-stilling-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  receivers:
    slack:
      channel: 'inkludering-alerts-prod'
  alerts:

    - alert: rekrutteringsbistand-stilling-api er nede
      severity: danger
      expr: sum(up{app="rekrutteringsbistand-stilling-api", job="kubernetes-pods"}) == 0
      for: 1s
      action: "https://logs.adeo.no/goto/628dd18b2a5496e186cb99f04cd6b32f"

    - alert: Det er logget errors i rekrutteringsbistand-stilling-api
      severity: danger
      expr: sum(increase(logd_messages_total{log_app="rekrutteringsbistand-stilling-api", log_level="Error"}[10m])) > 0
      for: 1s
      action: "https://logs.adeo.no/goto/628dd18b2a5496e186cb99f04cd6b32f"

    - alert: Det er logget warnings i rekrutteringsbistand-stilling-api
      severity: warning
      expr: sum(increase(logd_messages_total{log_app="rekrutteringsbistand-stilling-api", log_level="Warning"}[10m])) > 1
      for: 3m
      action: "https://logs.adeo.no/goto/628dd18b2a5496e186cb99f04cd6b32f"
