apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: rekrutteringsbistand-stilling-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  port: 9501
  ingresses:
    - https://rekrutteringsbistand-stilling-api.nais.adeo.no
    - https://rekrutteringsbistand-stilling-api.intern.nav.no
    - https://rekrutteringsbistand-stilling-api.prod-fss-pub.nais.io
  liveness:
    path: /internal/actuator/health
    initialDelay: 30
  readiness:
    path: /internal/actuator/health
    initialDelay: 30
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  vault:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: vis-stilling
          cluster: prod-gcp
        - application: rekrutteringsbistand-stilling-indekser
          cluster: prod-gcp
          namespace: toi
        - application: rekrutteringsbistand-container
          namespace: toi
          cluster: prod-gcp
        - application: rekrutteringsbistand-kandidat-api
          namespace: toi
          cluster: prod-fss
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: VIS_STILLING_CLIENT_ID
      value: 7f5d9ab4-7d8a-4a58-81dd-5972263c25ed
    - name: REKRUTTERINGSBISTAND_STILLING_INDEKSER_CLIENT_ID
      value: cc692cbe-7c85-471b-abab-24ae01c625da
